import type { Source } from "./types.js";

function clean(s: string): string {
  return s.replace(/[{}]/g, "").replace(/\s+/g, " ").trim();
}

// Stable-ish citation key: firstauthorlastname + year + first title word.
function bibKey(s: Source, used: Set<string>): string {
  const last = s.meta?.authors?.[0]?.split(/\s+/).pop()?.toLowerCase().replace(/[^a-z0-9]/g, "");
  const year = s.meta?.year ? String(s.meta.year) : "";
  const word = s.title
    .split(/\s+/)
    .find((w) => w.replace(/[^a-z0-9]/gi, "").length > 3)
    ?.toLowerCase()
    .replace(/[^a-z0-9]/g, "");
  let base = `${last ?? s.id.toLowerCase()}${year}${word ?? ""}` || s.id.toLowerCase();
  let key = base;
  let n = 2;
  while (used.has(key)) key = `${base}${n++}`;
  used.add(key);
  return key;
}

// Build a BibTeX file from the scholarly sources in a dossier (those carrying
// DOI / arXiv id / authors / year). Used for research mode's refs.bib.
export function toBibtex(sources: Source[]): string {
  const scholarly = sources.filter(
    (s) => s.meta && (s.meta.doi || s.meta.arxivId || (s.meta.authors && s.meta.authors.length) || s.meta.year),
  );
  if (!scholarly.length) {
    return "% No scholarly sources with citable metadata in this dossier.\n";
  }
  const used = new Set<string>();
  const out: string[] = ["% Generated by ultrasearch — research mode", ""];
  for (const s of scholarly) {
    const key = bibKey(s, used);
    const fields: string[] = [`  title = {${clean(s.title)}}`];
    if (s.meta?.authors?.length) fields.push(`  author = {${s.meta.authors.map(clean).join(" and ")}}`);
    if (s.meta?.year) fields.push(`  year = {${s.meta.year}}`);
    if (s.meta?.venue) fields.push(`  journal = {${clean(String(s.meta.venue))}}`);
    if (s.meta?.doi) fields.push(`  doi = {${clean(String(s.meta.doi))}}`);
    if (s.meta?.arxivId) {
      fields.push(`  eprint = {${clean(String(s.meta.arxivId))}}`);
      fields.push(`  archivePrefix = {arXiv}`);
    }
    if (s.url) fields.push(`  url = {${s.url}}`);
    fields.push(`  note = {ultrasearch source ${s.id}}`);
    out.push(`@article{${key},`);
    out.push(fields.join(",\n"));
    out.push(`}`);
    out.push("");
  }
  return out.join("\n");
}
